// <auto-generated />
using System;
using EmployeeMCrud.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeMCrud.Migrations
{
    [DbContext(typeof(APIDbContext))]
    partial class APIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
    

            modelBuilder.Entity("EmployeeMCrud.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"), 1L, 1);

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity<Employee>(b =>
            {
                b.Property<int>("EmployeeId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);
                b.Property<string>("EmployeeName")
                .IsRequired()
                .HasColumnType("varchar");
                

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("varchar(max)");

                b.Property<string>("LastName")
                    .HasColumnType("varchar(max)");

                b.Property<string>("Designation")
                    .IsRequired()
                    .HasColumnType("varchar(max)");

                b.Property<int?>("ReportingManagerEmployeeId")
                    .HasColumnType("int");

                b.Property<string>("Sex")
                    .HasColumnType("varchar(max)");

                b.Property<string>("EmployeeAddress")
                    .HasColumnType("varchar(max)");

                b.Property<string>("State")
                    .HasColumnType("varchar(max)");

                b.Property<string>("Country")
                    .HasColumnType("varchar(max)");

                b.Property<int?>("Pincode")
                    .HasColumnType("int");

                b.Property<int>("DepartmentId")
                    .HasColumnType("int");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.HasKey("EmployeeId");

                b.ToTable("Employee");
            });

        }
    }
}
